### ISSUE TITLE
Sharing Keychain

### ISSUE THREAD

**Issue by hitmanpt** [mattrubin/OneTimePassword#142]
I've been tweaking the code to be able to share the keychain

So far I was unable to do so.
So what have I done...
On the entitlements I added the keychain group

> SEED.bundle (this is a fake value just so you can have an idea, the app has the real code)

After having Key Sharing enabled for all apps with the group mentioned above I started tweaking with the Keychain.swift file

In the function
`private func addKeychainItem(withAttributes attributes: [String: AnyObject]) throws -> Data {`
added this line
`mutableAttributes[kSecAttrSynchronizable as String] = kCFBooleanTrue`

And other two functions
```
private func keychainItem(forPersistentRef persistentRef: Data) throws -> NSDictionary? {
private func allKeychainItems() throws -> [NSDictionary] {
```

Added the line
`kSecAttrSynchronizable as String:   kCFBooleanTrue,`

After all this the app was still working but the sync isn't, I figured out that I'm missing to witch group will the functions will access

so I created a constant
`private let kSAAGroup = "SEED.bundle"`

And on this function
`func keychainAttributes() throws -> [String: AnyObject] {`
I tried to add this line
`kSecAttrAccessGroup as String: kSAAGroup as NSString,`

From here the app stopped working properly giving me the error when trying to save a new token

> Keychain error: systemError(-34018)

From here I don't know what to do.

BTW: I'm not enrolled in the Apple Dev Program, I'm using the my Apple ID to sign the app
I'm running the app in a Device and not on a Simulator

Any help on this area?

**Comment by mattrubin** [comment]
Error [-34018 is errSecMissingEntitlement](https://www.osstatus.com/search/results?search=-34018) so it seems like you're missing or misusing an entitlement for keychain sharing. You may need an Apple Developer Program membership to get access to a valid app identifier prefix for your keychain access group.

Also, I don't know much about the topic, but at a quick glance it looks like you're mixing [`kSecAttrAccessGroup`](https://developer.apple.com/documentation/security/kSecAttrAccessGroup), which sets a keychain access group for sharing between apps from the same developer, and [`kSecAttrSynchronizable`](https://developer.apple.com/documentation/security/ksecattrsynchronizable), which allows a password to be synchronized via iCloud Keychain. I'm not sure if these keys are meant to be used together.

Since I'm currently not looking to add keychain sharing to this library (for security reasons) I'm going to close this issue. However, if you find a solution to your problem, feel free to post here in case others come looking for the same modification.
