### ISSUE TITLE
base32String do not match any available overload

### ISSUE THREAD

**Issue by THDEW** [mattrubin/OneTimePassword#144]
I implement OneTimePassword library in my project and then I try to do exactly the same as the example that provide on your github but I got this error
<img width="851" alt="screen shot 2560-07-21 at 4 33 31 pm" src="https://user-images.githubusercontent.com/16135333/28458394-cb02cff0-6e33-11e7-9dea-d583556e85d6.png">
Any idea on this error?

**Comment by mattrubin** [comment]
It looks like you're using the example code from the README in your checked-out copy of the repo, which was slightly out of date and [has since been corrected](https://github.com/mattrubin/OneTimePassword/pull/134). Try the updated example code here: https://github.com/mattrubin/OneTimePassword/blob/develop/README.md#create-a-token

``` swift
guard let secretData = MF_Base32Codec.data(fromBase32String: secretString),
```
